# 도커 빌드
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DOCKER_RDS_URL}
    username: ${DOCKER_RDS_USERNAME}
    password: ${DOCKER_RDS_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

jwt:
  secret: ${JWT_SECRET_KEY}

springdoc:
  use-fqn: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /**

cloud:
  aws:
    s3:
      bucket: koview
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    '[com.koview.koview_server]': INFO
    '[org.hibernate.type]': TRACE
