# 기본 로컬 빌드
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8000
spring:
  datasource:
    url: ${LOCAL_RDS_URL}
    username: root
    password: ${LOCAL_RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

jwt:
  secret: ${JWT_SECRET_KEY}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /**

cloud:
  aws:
    s3:
      bucket: koview
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    '[com.koview.koview_server]': INFO
    '[org.hibernate.type]': TRACE