version: '3'
services:
  kodb:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kodb
    ports:
      - 4000:3306
    volumes:
      - ./mysql/store:/var/lib/mysql
    networks:
      - network

  backend:
    build:
      context: ./koview-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://kodb:3306/kodb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - network
networks:
  network: