services:
  kodb:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kodb
    ports:
      - 4000:3306
    volumes:
      - ./mysql/store:/var/lib/mysql
    networks:
      - network

  backend:
    build:
      context: ./koview-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kodb
    environment:
      DOCKER_RDS_URL: ${DOCKER_RDS_URL}
      DOCKER_RDS_USERNAME: root
      DOCKER_RDS_PASSWORD: root
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - network
networks:
  network: