name: CI/CD Docker

on:
  push:
    branches: [ main, dev ]

env:
  DOCKER_IMAGE: tinywhale1031/koview-auto-deploy
  VERSION: ${{ github.sha }}
  NAME: koview_cicd
  AWS_RDS_URL: ${{ secrets.AWS_RDS_URL }}
  AWS_RDS_USERNAME: ${{ secrets.AWS_RDS_USERNAME }}
  AWS_RDS_PASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  SECRETE_ACTION_KEY: ${{ secrets.SECRETE_ACTION_KEY }}

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
          buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
          install: true
          use: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./koview-server
          file: ./koview-server/Dockerfile.prod
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1

  deploy:
    needs: build_and_push
    name: Deploy Docker Image
    runs-on: [self-hosted, label-go] # AWS ./configure에서 사용할 label 명
    steps:
      - name: Install AWS CLI
        run: |
          sudo yum update -y
          sudo yum install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ env.SECRETE_ACTION_KEY }}

      - name: EC2 Run Commands
        run: |
          sudo docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}
          sudo docker stop ${{ env.NAME }} || true
          sudo docker rm ${{ env.NAME }} || true
          sudo docker pull ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          sudo docker run -d -p 8080:8080 --name ${{ env.NAME }} \
            --env AWS_RDS_URL=${{ env.AWS_RDS_URL }} \
            --env AWS_RDS_USERNAME=${{ env.AWS_RDS_USERNAME }} \
            --env AWS_RDS_PASSWORD=${{ env.AWS_RDS_PASSWORD }} \
            --env JWT_SECRET_KEY=${{ env.JWT_SECRET_KEY }} \
            --env AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} \
            --env AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }} \
            --restart always ${{ env.DOCKER_IMAGE }}:${{ github.sha }}


